export { auditBimi } from './bimi'
export { auditDkim } from './dkim'
export { auditDmarc } from './dmarc'
export type { DnsResolver } from './dns'
export { auditDomain, createResolver, DohResolver, NodeDnsResolver } from './dns'
export { auditMtaSts } from './mta-sts'
export { formatJson, formatReport } from './report'
export { auditSpf } from './spf'
export type { BimiResult, DkimResult, DmarcResult, DnsAuditResult, MtaStsResult, SpfResult } from './types'
export type { WatchConfig } from './watch'
export { createWatcher } from './watch'
